---
title: "ggplot2 Notebook"
output: html_notebook
---

# ggplot library

```{r}
library(tidyverse)
library(ggThemeAssist)
```


```{r plot 1}
ggplot(data= mpg) +
  geom_point( aes(x= displ, y=hwy))

```



```{r plot 2}
ggplot(data= mpg) +
  geom_point( aes(x= displ, y=hwy, color= class))

```





```{r plot 3}
ggplot(data= mpg) +
  geom_point( aes(x= displ, y=hwy, size= class), color= "orange")

```











```{r plot 4}
ggplot(data= mpg) +
  geom_bar( aes(x= class), fill='red')

```







```{r plot 5}
ggplot(mpg) +
  geom_histogram( aes(x= hwy), 
                  binwidth = 5, 
                  fill="gold", 
                  color='black') +
  scale_x_continuous(breaks = seq(0,45,5), limits =  c(0,50), expand = c(0,0))+
  scale_y_continuous(breaks = seq(0,90,10), limits =  c(0,90), expand = c(0,0))
# scale the data


```





```{r plot 6}
ggplot(mpg) +
  geom_boxplot( aes(x= class, y=cty, fill=class))

```








```{r plot 7}
ggplot(mpg) +
  geom_bar( aes(x= class, fill= factor(cyl))) +
  labs(title = "cylinders by class", fill="cylinders") +
  coord_flip()

```


```{r plot 8}
ggplot(mpg) +
  geom_bar( aes(x= class, fill= factor(cyl)), position = 'dodge') +
  labs(title = "cylinders by class", fill="cylinders") +
  coord_flip()

```





























